### ISSUE TITLE
yml

### ISSUE THREAD

**Issue by nuoxoxo** [nuoxoxo/nuoxoxo#1]
```yml
# This is a basic workflow to help you get started with Actions

name: daily snake

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: CHECKOUT
        uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: SNAKE
        uses: Platane/snk@master
        id: snake_svg
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: ./assets/github-contribution-grid-snake.svg
      - name: PUSH
        uses: EndBug/add-and-commit@v9
        with:
          branch: main
          message: "daily : snake gen"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

```
